# Generated by Django 3.0.3 on 2020-03-04 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20200304_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='room_image',
        ),
    ]
