# Generated by Django 3.0.3 on 2020-03-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_rooms_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='room_image',
            field=models.ImageField(default='0.jpeg', upload_to='media'),
        ),
    ]
