# Generated by Django 3.0.3 on 2020-03-05 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_booked_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='status',
        ),
    ]
