# Generated by Django 3.0.3 on 2020-03-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='roommanager',
            name='phone_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='roommanager',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
